In [1]:
from annotator import Annotator
from datasets import AGRDataset

from pathlib import Path
import pandas as pd

In [2]:
# Resolves the cache, lazily builds/loads the gene index. Omit the path for the home-cache default.
# One Annotator serves any genome; taxon is passed per call.
ann = Annotator(Path("/lab01/Projects/Lionel_Projects/alliance_wrapper/cache"))

In [3]:
# Optional one-time bulk pull: orthology -> cache/bulk/orthology.parquet (the .tsv.gz is discarded).
await ann.download(AGRDataset.ORTHOLOGY)

PosixPath('/lab01/Projects/Lionel_Projects/alliance_wrapper/cache/bulk/orthology.parquet')

In [4]:
normalize = await ann.annotate(["TP53", "BRCA1", "EGFR", "RPA1", "CELSR3", "NOTAGENE", "C2orf40"], limit=5, case_insensitive=True)
normalize

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,GeneBioTypeId,GeneBioTypeName,GeneAllianceAutomatedDescription,GeneMODAutomatedDescription,GeneMODDescription,Assembly,Chromosome,StartPosition,EndPosition,Strand
0,TP53,OFFICIAL_SYMBOL,NCBITaxon:8364,Xenopus tropicalis,Xenbase:XB-GENE-484286,tp53,p53|Trp248|tumor suppressor p53|Xp53|Xrel3,NaN,NaN,Xenbase:XB-GENEPAGE-484285|ENSEMBL:ENSXETG0000...,SO:0000704,gene,Predicted to enable DNA-binding transcription ...,NaN,NaN,XT10.0,Chr3,153630573,153641544,+
1,TP53,OFFICIAL_SYMBOL,NCBITaxon:7955,Danio rerio,ZFIN:ZDB-GENE-990415-270,tp53,brp53|drp53|etID22686.5|fb40d06|p53|wu:fb40d06...,NaN,NaN,UniProtKB:B0R0M3|UniProtKB:A0A8M2BCD8|UniProtK...,SO:0001217,protein_coding_gene,Enables DNA-binding transcription factor activ...,NaN,NaN,GRCz11,5,24086227,24097805,+
2,TP53,OFFICIAL_SYMBOL,NCBITaxon:10116,Rattus norvegicus,RGD:3889,Tp53,p53|Trp53|tumor protein p53 (Li-Fraumeni syndr...,NaN,NaN,UniProtKB:Q66HM0|UniProtKB:A6HFR8|UniProtKB:Q9...,SO:0001217,protein_coding_gene,"Enables several functions, including MDM2/MDM4...",NaN,"Enables several functions, including MDM2/MDM4...",mRatBN7.2,10,54300048,54311525,+
3,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,SO:0001217,protein_coding_gene,"Enables several functions, including DNA bindi...",NaN,This gene encodes a tumor suppressor protein c...,GRCh38,17,7661779,7687550,-
4,TP53,SYNONYM,NCBITaxon:7227,Drosophila melanogaster,FB:FBgn0035542,TP53INP,CG11347|DOR|dDOR|TP53|Diabetes and obesity reg...,CG11347,FB:CG11347,UniProtKB:Q8IRB4|UniProtKB:Q9VZC7|NCBI_Gene:38...,SO:0001217,protein_coding_gene,Enables nuclear receptor binding activity and ...,NaN,Tumor protein p53 inducible nuclear protein (T...,R6,3L,4406943,4420648,+
5,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,SO:0001217,protein_coding_gene,"Enables several functions, including enzyme bi...",NaN,This gene encodes a 190 kD nuclear phosphoprot...,GRCh38,17,43044292,43170327,-
6,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:8364,Xenopus tropicalis,Xenbase:XB-GENE-490624,brca1,breast and ovarian cancer susceptibility protein,NaN,NaN,Xenbase:XB-GENEPAGE-490623|ENSEMBL:ENSXETG0000...,SO:0000704,gene,Predicted to enable ubiquitin-protein transfer...,NaN,NaN,XT10.0,Chr10,19543821,19614899,-
7,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:10090,Mus musculus,MGI:104537,Brca1,NaN,NaN,NaN,UniProtKB:A0A087WP26|UniProtKB:A0A087WPE1|UniP...,SO:0001217,protein_coding_gene,Enables damaged DNA binding activity; transcri...,NaN,Homozygous null mutants are embryonic lethal w...,GRCm39,11,101379587,101442808,-
8,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:10116,Rattus norvegicus,RGD:2218,Brca1,breast cancer type 1 susceptibility protein ho...,NaN,NaN,UniProtKB:B0FT14|UniProtKB:G3V8S5|UniProtKB:A0...,SO:0001217,protein_coding_gene,Enables chromatin binding activity. Involved i...,NaN,Enables chromatin binding activity. Involved i...,mRatBN7.2,10,86417441,86477762,-
9,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,SO:0001217,protein_coding_gene,"Enables several functions, including actin fil...",NaN,The protein encoded by this gene is a transmem...,GRCh38,7,55018820,55211628,+
10,EGFR,OFFICIAL_SYMBOL,NCBITaxon:10116,Rattus norvegicus,RGD:2543,Egfr,"ERBB1|Epidermal growth factor receptor, former...",NaN,RGD:68937,UniProtKB:A6JPX9|UniProtKB:Q9QX70|UniProtKB:G3...,SO:0001217,protein_coding_gene,"Enables several functions, including calmoduli...",NaN,"Enables several functions, including calmoduli...",mRatBN7.2,14,91176979,91349722,+
11,EGFR,OFFICIAL_SYMBOL,NCBITaxon:10090,Mus musculus,MGI:95294,Egfr,avian erythroblastic leukemia viral (v-erb-b) ...,NaN,NaN,NCBI_Gene:13649|ENSEMBL:ENSMUSG00000020122|Uni...,SO:0001217,protein_coding_gene,Enables epidermal growth factor binding activi...,NaN,Mutations widely affect epithelial development...,GRCm39,11,16700153,16868158,+
12,EGFR,OFFICIAL_SYMBOL,NCBITaxon:7227,Drosophila melanogaster,FB:FBgn0003731,Egfr,flb|DER|top|Ellipse|EGF receptor|EGfr|torpedo|...,CG10079,FB:FBgn0010599|FB:FBgn0022793|FB:CG10079,UniProtKB:Q8MLW0|NCBI_Gene:37455|UniProtKB:Q6S...,SO:0001217,protein_coding_gene,Predicted to enable transmembrane receptor pro...,NaN,Epidermal growth factor receptor (Egfr) encode...,R6,2R,21522420,21559977,+
13,EGFR,OFFICIAL_SYMBOL,NCBITaxon:8364,Xenopus tropicalis,Xenbase:XB-GENE-6067152,egfr,erbb|erbb1|her1|XEgfr,NaN,NaN,Xenbase:XB-GENEPAGE-6067151|ENSEMBL:ENSXETG000...,SO:0000704,gene,Predicted to enable epidermal growth factor bi...,NaN,NaN,XT10.0,Chr6,56743898,56899933,+
14,RPA1,OFFICIAL_SYMBOL,NCBITaxon:7955,Danio rerio,ZFIN:ZDB-GENE-030912-3,rpa1,wu:fi14b08|zgc:55337|zgc:77092,NaN,NaN,UniProtKB:Q6NY74|PANTHER:PTHR23273|NCBI_Gene:3...,SO:0001217,protein_coding_gene,Predicted to enable damaged DNA binding activi...,NaN,NaN,GRCz11,15,26498339,26538989,-
15,RPA1,OFFICIAL_SYMBOL,NCBITaxon:8364,Xenopus tropicalis,Xenbase:XB-GENE-945047,rpa1,hssb|mst075|repa1|rf-a|rp-a|rpa|rpa70,NaN,NaN,Xenbase:XB-GENEPAGE-945046|ENSEMBL:ENSXETG0000...,SO:0000704,gene,Predicted to enable damaged DNA binding activi...,NaN,NaN,XT10.0,Chr2,36006987,36045697,-
16,RPA1,OFFICIAL_SYMBOL,NCBITaxon:10090,Mus musculus,MGI:1915525,Rpa1,5031405K23Rik|RP-A|RF-A|Rpa|70kDa|replication ...,NaN,NaN,NCBI_Gene:68275|UniProtKB:Q3U8B3|UniProtKB:Q5S...,SO:0001217,protein_coding_gene,Enables chromatin binding activity. Acts upstr...,NaN,Homozygous null mice display embryonic lethali...,GRCm39,11,75188992,75239478,-
17,RPA1,OFFICIAL_SYMBOL,NCBITaxon:10116,Rattus norvegicus,RGD:1307376,Rpa1,LOC287524|Cb1-727|replication protein A 70 kDa...,NaN,NaN,UniProtKB:A6HGQ0|UniProtKB:A0A0G2KAT3|UniProtK...,SO:0001217,protein_coding_gene,Enables single-stranded DNA binding activity. ...,NaN,Enables single-stranded DNA binding activity. ...,mRatBN7.2,10,60148793,60199970,-
18,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,SO:0001217,protein_coding_gene,Enables G-rich strand telomeric DNA binding ac...,NaN,This gene encodes the largest subunit of the h...,GRCh38,17,1829702,1900082,+
19,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:7955,Danio rerio,ZFIN:ZDB-GENE-070122-3,celsr3,NaN,NaN,NaN,ENSEMBL:ENSDARG00000055825|NCBI_Gene:100008568...,SO:0001217,protein_coding_gene,Predicted to enable G protein-coupled receptor...,NaN,NaN,GRCz11,8,26125218,26212523,+
20,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:8364,Xenopus tropicalis,Xenbase:XB-GENE-852799,celsr3,LOC108714671|LOC108715881,NaN,NaN,Xenbase:XB-GENEPAGE-852798|ENSEMBL:ENSXETG0000...,SO:0000704,gene,Predicted to enable beta-catenin binding activ...,NaN,NaN,XT10.0,Chr4,135982112,136099207,-
21,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,SO:0001217,protein_coding_gene,Predicted to enable G protein-coupled receptor...,NaN,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+
22,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:10116,Rattus norvegicus,RGD:621787,Celsr3,Megf2|cadherin EGF LAG seven-pass G-type recep...,NaN,NaN,UniProtKB:A6I391|UniProtKB:A0A8I6A2Y0|UniProtK...,SO:0001217,protein_coding_gene,Predicted to enable G protein-coupled receptor...,NaN,Predicted to enable G protein-coupled receptor...,mRatBN7.2,8,109530597,109558360,+
23,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,SO:0001217,protein_coding_gene,Predicted to enable G protein-coupled receptor...,NaN,"This gene belongs to the flamingo subfamily, w...",GRCh38,3,48636463,48662886,-
24,NOTAGENE,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,C2orf40,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:24642,ECRG4,C2orf40|chromosome 2 open reading frame 40|aug...,NaN,RGD:1603606,UniProtKB:D3DVK2|UniProtKB:C9JRR0|UniProtKB:B8...,SO:0001217,protein_coding_gene,Enables neuropeptide hormone activity. Involve...,NaN,Enables neuropeptide hormone activity. Involve...,GRCh38,2,106063241,106078155,+
26,C2orf40,SYNONYM,NCBITaxon:8355,Xenopus laevis,Xenbase:XB-GENE-997590,ecrg4.L,c2orf40|esophageal cancer related gene 4,NaN,NaN,Xenbase:XB-GENEPAGE-997586|NCBI_Gene:373779|Re...,SO:0000704,gene,Predicted to be located in apical plasma membr...,NaN,NaN,XL10.1,Chr2L,114394778,114404735,-
27,C2orf40,SYNONYM,NCBITaxon:8364,Xenopus tropicalis,Xenbase:XB-GENE-997587,ecrg4,c2orf40|esophageal cancer related gene 4,NaN,NaN,Xenbase:XB-GENEPAGE-997586|ENSEMBL:ENSXETG0000...,SO:0000704,gene,Predicted to be located in apical plasma membr...,NaN,NaN,XT10.0,Chr2,110047671,110061840,-
28,C2orf40,SYNONYM,NCBITaxon:8355,Xenopus laevis,Xenbase:XB-GENE-17335346,ecrg4.S,c2orf40|esophageal cancer related gene 4,NaN,NaN,Xenbase:XB-GENEPAGE-997586|NCBI_Gene:108709698...,SO:0000704,gene,Orthologous to human ECRG4 (ECRG4 augurin prec...,NaN,NaN,XL10.1,Chr2S,101412752,101423734,-

In [5]:
# Annotate a human gene list against orthology. Unmatched queries are retained with null cells.
orth = await ann.annotate(["TP53", "BRCA1", "EGFR", "RPA1", "CELSR3", "NOTAGENE"], AGRDataset.ORTHOLOGY, taxon="human", limit=2)
orth

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,...,Gene1SpeciesName,Gene2ID,Gene2Symbol,Gene2SpeciesTaxonID,Gene2SpeciesName,Algorithms,AlgorithmsMatch,OutOfAlgorithms,IsBestScore,IsBestRevScore
0,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,Xenbase:XB-GENE-6252168,tp53.L,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
1,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,Xenbase:XB-GENE-484286,tp53,NCBITaxon:8364,NaN,Hieranoid|InParanoid|OMA|OrthoFinder|OrthoInsp...,8,9,Yes,Yes
2,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,FB:FBgn0039044,p53,NCBITaxon:7227,NaN,Ensembl Compara|OrthoFinder|OrthoInspector|PAN...,6,9,Yes,Yes
3,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,MGI:98834,Trp53,NCBITaxon:10090,NaN,HGNC|Hieranoid|InParanoid|OMA|OrthoFinder|Orth...,9,10,Yes,Yes
4,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,ZFIN:ZDB-GENE-990415-270,tp53,NCBITaxon:7955,NaN,Hieranoid|InParanoid|OMA|OrthoFinder|OrthoInsp...,9,10,Yes,Yes
5,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,Xenbase:XB-GENE-17346471,tp53.S,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
6,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,RGD:3889,Tp53,NCBITaxon:10116,NaN,Hieranoid|InParanoid|OMA|OrthoFinder|OrthoInsp...,9,10,Yes,Yes
7,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,MGI:1351320,Trp53bp1,NCBITaxon:10090,NaN,Ensembl Compara|HGNC|Hieranoid|InParanoid|OMA|...,10,10,Yes,Yes
8,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,Xenbase:XB-GENE-17336999,tp53bp1.L,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
9,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,Xenbase:XB-GENE-1010618,tp53bp1.S,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
10,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,SGD:S000002625,RAD9,NCBITaxon:559292,NaN,OrthoFinder|PANTHER,2,9,Yes,Yes
11,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,RGD:1308039,Tp53bp1,NCBITaxon:10116,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
12,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,Xenbase:XB-GENE-1010615,tp53bp1,NCBITaxon:8364,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
13,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,ZFIN:ZDB-GENE-030131-3695,tp53bp1,NCBITaxon:7955,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
14,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,...,NaN,WB:WBGene00002027,hsr-9,NCBITaxon:6239,NaN,Ensembl Compara|OrthoFinder|OrthoInspector|PAN...,4,9,Yes,Yes
15,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,...,NaN,RGD:2218,Brca1,NCBITaxon:10116,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
16,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,...,NaN,Xenbase:XB-GENE-6254021,brca1.L,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
17,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,...,NaN,WB:WBGene00000264,brc-1,NCBITaxon:6239,NaN,OrthoInspector|PANTHER,2,9,Yes,Yes
18,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,...,NaN,MGI:104537,Brca1,NCBITaxon:10090,NaN,Ensembl Compara|HGNC|Hieranoid|InParanoid|OMA|...,10,10,Yes,Yes
19,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,...,NaN,Xenbase:XB-GENE-490624,brca1,NCBITaxon:8364,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,8,9,Yes,Yes
20,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,WB:WBGene00002299,let-23,NCBITaxon:6239,NaN,Hieranoid|InParanoid|OMA|OrthoFinder|OrthoInsp...,8,9,Yes,No
21,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,RGD:2543,Egfr,NCBITaxon:10116,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
22,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,Xenbase:XB-GENE-6067152,egfr,NCBITaxon:8364,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
23,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,Xenbase:XB-GENE-17334442,egfr.S,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
24,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,Xenbase:XB-GENE-6067157,egfr.L,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
25,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,FB:FBgn0003731,Egfr,NCBITaxon:7227,NaN,Hieranoid|InParanoid|OMA|OrthoFinder|OrthoInsp...,8,9,Yes,No
26,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,MGI:95294,Egfr,NCBITaxon:10090,NaN,Ensembl Compara|HGNC|Hieranoid|InParanoid|OMA|...,10,10,Yes,Yes
27,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,ZFIN:ZDB-GENE-030918-1,egfra,NCBITaxon:7955,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
28,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,ZFIN:ZDB-GENE-100308-1,egfrb,NCBITaxon:7955,NaN,ZFIN,1,10,No,Yes
29,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,WB:WBGene00017546,rpa-1,NCBITaxon:6239,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
30,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,MGI:1915525,Rpa1,NCBITaxon:10090,NaN,Ensembl Compara|HGNC|Hieranoid|InParanoid|OMA|...,10,10,Yes,Yes
31,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,Xenbase:XB-GENE-945055,rpa1.L,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
32,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,FB:FBgn0010173,RPA1,NCBITaxon:7227,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
33,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,Xenbase:XB-GENE-945047,rpa1,NCBITaxon:8364,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
34,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,SGD:S000000065,RFA1,NCBITaxon:559292,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
35,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,Xenbase:XB-GENE-17344439,rpa1.S,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
36,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,ZFIN:ZDB-GENE-030912-3,rpa1,NCBITaxon:7955,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
37,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,WB:WBGene00019859,R03H10.7,NCBITaxon:6239,NaN,Ensembl Compara|PANTHER|PhylomeDB,3,9,No,Yes
38,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,...,NaN,RGD:1307376,Rpa1,NCBITaxon:10116,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
39,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,ZFIN:ZDB-GENE-030131-5286,polr1a,NCBITaxon:7955,NaN,ZFIN,1,10,Yes,Yes
40,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,MGI:1096397,Polr1a,NCBITaxon:10090,NaN,Ensembl Compara|HGNC|Hieranoid|InParanoid|OMA|...,10,10,Yes,Yes
41,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,FB:FBgn0019938,Polr1A,NCBITaxon:7227,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,8,9,Yes,Yes
42,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,RGD:620824,Polr1a,NCBITaxon:10116,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
43,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,Xenbase:XB-GENE-1005160,polr1a,NCBITaxon:8364,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
44,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,Xenbase:XB-GENE-1005163,polr1a.L,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
45,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,SGD:S000005868,RPA190,NCBITaxon:559292,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
46,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,...,NaN,WB:WBGene00012999,rpoa-1,NCBITaxon:6239,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
47,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,Xenbase:XB-GENE-852799,celsr3,NCBITaxon:8364,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,8,9,Yes,Yes
48,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,Xenbase:XB-GENE-17342205,celsr3.L,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
49,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,WB:WBGene00001475,fmi-1,NCBITaxon:6239,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
50,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,RGD:621787,Celsr3,NCBITaxon:10116,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,10,10,Yes,Yes
51,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,Xenbase:XB-GENE-17342206,celsr3.S,NCBITaxon:8355,NaN,Xenbase,1,1,Yes,Yes
52,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,FB:FBgn0024836,stan,NCBITaxon:7227,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,9,Yes,Yes
53,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,ZFIN:ZDB-GENE-070122-3,celsr3,NCBITaxon:7955,NaN,Ensembl Compara|Hieranoid|InParanoid|OMA|Ortho...,9,10,Yes,Yes
54,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,...,NaN,MGI:1858236,Celsr3,NCBITaxon:10090,NaN,Ensembl Compara|HGNC|Hieranoid|InParanoid|OMA|...,10,10,Yes,Yes
55,NOTAGENE,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Filter-then-requery: pull the mouse orthologs back out as a fresh gene list.
mouse_ids = orth.loc[orth.Gene2SpeciesTaxonID == "NCBITaxon:10090", "Gene2ID"].dropna().unique().tolist()
mouse_ids

['MGI:98834',
 'MGI:1351320',
 'MGI:104537',
 'MGI:95294',
 'MGI:1915525',
 'MGI:1096397',
 'MGI:1858236']

In [7]:
# Per-gene API path (phenotypes have no bulk TSV): paginated + cached under cache/api/phenotypes/.
pheno = await ann.annotate(mouse_ids, AGRDataset.PHENOTYPES, taxon="mouse")
pheno

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,...,GeneAllianceAutomatedDescription,GeneMODAutomatedDescription,GeneMODDescription,Assembly,Chromosome,StartPosition,EndPosition,Strand,phenotypeStatement,references
0,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Enables MDM2/MDM4 family protein binding activ...,NaN,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,abnormal abdominal lymph node morphology,PMID:24013501
1,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Enables MDM2/MDM4 family protein binding activ...,NaN,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,abnormal apoptosis,PMID:14702042
2,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Enables MDM2/MDM4 family protein binding activ...,NaN,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,abnormal atrioventricular cushion morphology,PMID:25119037
3,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Enables MDM2/MDM4 family protein binding activ...,NaN,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,abnormal cardiac outflow tract development,PMID:25119037
4,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Enables MDM2/MDM4 family protein binding activ...,NaN,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,abnormal cardiovascular system physiology,PMID:17334357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Predicted to enable G protein-coupled receptor...,NaN,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,impaired coordination,PMID:15778712
687,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Predicted to enable G protein-coupled receptor...,NaN,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,impaired neuronal migration,PMID:19332558
688,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Predicted to enable G protein-coupled receptor...,NaN,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,meteorism,PMID:15778712
689,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Predicted to enable G protein-coupled receptor...,NaN,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,"neonatal lethality, complete penetrance",PMID:19332558|PMID:15778712
690,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Predicted to enable G protein-coupled receptor...,NaN,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,respiratory failure,PMID:15778712

In [8]:
# Ingest an external annotation table; its gene ids are normalized to canonical GeneId.
panel = pd.DataFrame({"symbol": ["TP53", "BRCA1", "EGFR"], "panel_score": [9.1, 7.4, 6.2]})
await ann.ingest_annotation(panel, "panel", gene_id_column="symbol", taxon="human", override=True)

({'annotation_name': 'panel',
  'rows_in': 3,
  'rows_stored': 3,
  'rows_dropped_unmapped': 0,
  'normalized': True},
 Empty DataFrame
 Columns: [symbol, panel_score, GeneId]
 Index: [])

In [ ]:
brainspan_path = "/nfs/xing_lab/lab02/Data_Raw/Xiaolong/HumanCommon/Expression/BrainSpan/20190508BrainSpanGeneExpression.csv"
sfari_path = "/lab01/Projects/Lionel_Projects/biodatabases/SFARI/SFARI-Gene_genes_08-19-2024release_10-06-2024export.csv"
cao_ndd_path = "/lab01/Projects/Lionel_Projects/biodatabases/Cao_NDD_Candidate_Genes.tsv"

brainspan_df = pd.read_csv(brainspan_path, sep="\t", comment="#")
sfari_df = pd.read_csv(sfari_path, sep=",", comment="#")
cao_ndd_df = pd.read_csv(cao_ndd_path, sep="\t", comment="#")

# Prepend ENSEMBL prefix to BrainSpan gene IDs to match the format in the gene index, enabling cross-referencing during ingestion.
brainspan_df = brainspan_df.copy()
brainspan_df['ensembl_gene_id_full'] = brainspan_df['ensembl_gene_id'].map(lambda x: f"ENSEMBL:{x}")

brainspan_res, brainspan_unmapped = await ann.ingest_annotation(brainspan_df, "brainspan", gene_id_column=["geneSymbol", "ensembl_gene_id_full"], taxon="human", override=True, case_insensitive=True)
sfari_res, sfari_unmapped = await ann.ingest_annotation(sfari_df, "sfari", gene_id_column="gene-symbol", taxon="human", override=True, case_insensitive=True)
cao_ndd_res, cao_ndd_unmapped = await ann.ingest_annotation(cao_ndd_df, "cao_ndd", gene_id_column="hgnc_id", taxon="human", override=True, case_insensitive=True)

print("BrainSpan Ingestion Result:", brainspan_res)
print("SFARI Ingestion Result:", sfari_res)
print("Cao NDD Ingestion Result:", cao_ndd_res)

BrainSpan Ingestion Result: {'annotation_name': 'brainspan', 'rows_in': 52376, 'rows_stored': 37902, 'rows_dropped_unmapped': 14474, 'normalized': True}
SFARI Ingestion Result: {'annotation_name': 'sfari', 'rows_in': 1191, 'rows_stored': 1188, 'rows_dropped_unmapped': 3, 'normalized': True}
Cao NDD Ingestion Result: {'annotation_name': 'cao_ndd', 'rows_in': 2345, 'rows_stored': 2344, 'rows_dropped_unmapped': 1, 'normalized': True}

In [17]:
# External annotations join by name, contributing `panel.`-prefixed columns.
await ann.annotate(["TP53", "BRCA1", "EGFR"], "panel", "brainspan", "sfari", "cao_ndd", taxon="human")

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,...,cao_ndd.hgnc_id,cao_ndd.TD_multiplex_family,cao_ndd.TD_multiplex,cao_ndd.TD_simplex,cao_ndd.TD_CNV,cao_ndd.OCD,cao_ndd.ADHD,cao_ndd.ASDhigh,cao_ndd.ASDlow,cao_ndd.otherNeuro
0,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,HGNC:3236,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0