In [1]:
from geneharmony import Annotator, AGRDataset, taxon_mapper, TaxonField

from pathlib import Path
import pandas as pd

In [2]:
# init annotator with cache directory
ann = Annotator(Path("/lab01/Projects/Lionel_Projects/geneharmony/cache"))

In [3]:
# Optional one-time bulk pull: orthology -> cache/bulk/orthology.parquet (the .tsv.gz is discarded).
await ann.download(AGRDataset.ORTHOLOGY)

PosixPath('/lab01/Projects/Lionel_Projects/geneharmony/cache/bulk/orthology.parquet')

In [4]:
test = await ann.annotate(['BRCA1', 'IHG1'], limit = 2)
display(test)

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,GeneBioTypeId,GeneBioTypeName,GeneAllianceAutomatedDescription,GeneMODAutomatedDescription,GeneMODDescription,Assembly,Chromosome,StartPosition,EndPosition,Strand
0,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,SO:0001217,protein_coding_gene,"Enables several functions, including enzyme bi...",NaN,This gene encodes a 190 kD nuclear phosphoprot...,GRCh38,17,43044292,43170327,-
1,IHG1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:3800,FOXC1,forkhead box C1 protein|ARA|IGDA|IHG1|FKHL7|IR...,NaN,RGD:1353830|RGD:1346066,RGD:1353830|ENSEMBL:ENSG00000054598|NCBI_Gene:...,SO:0001217,protein_coding_gene,Enables DNA binding activity; DNA-binding tran...,NaN,This gene belongs to the forkhead family of tr...,GRCh38,6,1609915,1613897,+
2,IHG1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:26053,THG1L,putative tRNA(His) guanylyltransferase|hTHG1|I...,NaN,RGD:1603030,RGD:1603030|ENSEMBL:ENSG00000113272|NCBI_Gene:...,SO:0001217,protein_coding_gene,"Enables several functions, including guanyl-nu...",NaN,The protein encoded by this gene is a mitochon...,GRCh38,5,157731412,157741449,+

In [5]:
normalize = await ann.annotate(["TP53", "BRCA1", "EGFR", "RPA1", "CELSR3", "NOTAGENE", "C2orf40"], limit=5, case_insensitive=False)
normalize

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,GeneBioTypeId,GeneBioTypeName,GeneAllianceAutomatedDescription,GeneMODAutomatedDescription,GeneMODDescription,Assembly,Chromosome,StartPosition,EndPosition,Strand
0,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,SO:0001217,protein_coding_gene,"Enables several functions, including DNA bindi...",NaN,This gene encodes a tumor suppressor protein c...,GRCh38,17,7661779,7687550,-
1,TP53,SYNONYM,NCBITaxon:7227,Drosophila melanogaster,FB:FBgn0035542,TP53INP,CG11347|DOR|dDOR|TP53|Diabetes and obesity reg...,CG11347,FB:CG11347,UniProtKB:Q8IRB4|UniProtKB:Q9VZC7|NCBI_Gene:38...,SO:0001217,protein_coding_gene,Enables nuclear receptor binding activity and ...,NaN,Tumor protein p53 inducible nuclear protein (T...,R6,3L,4406943,4420648,+
2,TP53,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:11999,TP53BP1,p202|53BP1|FLJ41424|MGC138366|tumor suppressor...,NaN,RGD:1317577,UniProtKB:B7Z3E7|UniProtKB:Q7Z3U4|UniProtKB:M0...,SO:0001217,protein_coding_gene,"Enables several functions, including histone r...",NaN,This gene encodes a protein that functions in ...,GRCh38,15,43403061,43510728,-
3,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,SO:0001217,protein_coding_gene,"Enables several functions, including enzyme bi...",NaN,This gene encodes a 190 kD nuclear phosphoprot...,GRCh38,17,43044292,43170327,-
4,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,SO:0001217,protein_coding_gene,"Enables several functions, including actin fil...",NaN,The protein encoded by this gene is a transmem...,GRCh38,7,55018820,55211628,+
5,EGFR,SYNONYM,NCBITaxon:7227,Drosophila melanogaster,FB:FBgn0003731,Egfr,flb|DER|top|Ellipse|EGF receptor|EGfr|torpedo|...,CG10079,FB:FBgn0010599|FB:FBgn0022793|FB:CG10079,UniProtKB:Q8MLW0|NCBI_Gene:37455|UniProtKB:Q6S...,SO:0001217,protein_coding_gene,Predicted to enable transmembrane receptor pro...,NaN,Epidermal growth factor receptor (Egfr) encode...,R6,2R,21522420,21559977,+
6,RPA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:10289,RPA1,HSSB|RF-A|RP-A|REPA1|RPA70|MST075|replication ...,NaN,RGD:1316541,RGD:1316541|ENSEMBL:ENSG00000132383|NCBI_Gene:...,SO:0001217,protein_coding_gene,Enables G-rich strand telomeric DNA binding ac...,NaN,This gene encodes the largest subunit of the h...,GRCh38,17,1829702,1900082,+
7,RPA1,OFFICIAL_SYMBOL,NCBITaxon:7227,Drosophila melanogaster,FB:FBgn0010173,RPA1,rpa70|RpA-70|Rpa-70|RPA|dRP-A|CG9633|RpA70|D-S...,CG9633,FB:CG9633,NCBI_Gene:40972|UniProtKB:Q24492 (GCRP),SO:0001217,protein_coding_gene,Enables single-stranded DNA binding activity. ...,NaN,NaN,R6,3R,8262120,8264451,-
8,RPA1,SYNONYM,NCBITaxon:7227,Drosophila melanogaster,FB:FBgn0019938,Polr1A,RpI1|DmRPA1|RNA polymerase I|RPA190|153129_at|...,CG10122,FB:CG10122,NCBI_Gene:36617|UniProtKB:P91875 (GCRP),SO:0001217,protein_coding_gene,Predicted to enable 5'-3' RNA polymerase activ...,NaN,NaN,R6,2R,14595611,14601216,-
9,RPA1,SYNONYM,NCBITaxon:559292,Saccharomyces cerevisiae S288C,SGD:S000000065,RFA1,BUF2|FUN3|RPA1|RPA70,YAR007C,SGD:L000000204|SGD:L000001620,DIP:2512|CGD:orf19.2093|PomBase:SPBC660.13c|NC...,SO:0001217,protein_coding_gene,Enables double-stranded DNA binding activity; ...,NaN,Subunit of heterotrimeric Replication Protein ...,R64-5-1,chrI,156681,158715,-
10,RPA1,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:17264,POLR1A,A190|RPA1|RPO14|RPA194|RPO1-4|FLJ21915|MGC8796...,NaN,RGD:1345694,RGD:1345694|ENSEMBL:ENSG00000068654|NCBI_Gene:...,SO:0001217,protein_coding_gene,"Enables several functions, including DNA-direc...",NaN,The protein encoded by this gene is the larges...,GRCh38,2,86020216,86106155,-
11,CELSR3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3230,CELSR3,"cadherin, EGF LAG seven-pass G-type receptor 3...",NaN,RGD:1342685,UniProtKB:L0R6E8|UniProtKB:O75092|OMIM:604264|...,SO:0001217,protein_coding_gene,Predicted to enable G protein-coupled receptor...,NaN,"This gene belongs to the flamingo subfamily, w...",GRCh38,3,48636463,48662886,-
12,NOTAGENE,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,C2orf40,SYNONYM,NCBITaxon:9606,Homo sapiens,HGNC:24642,ECRG4,C2orf40|chromosome 2 open reading frame 40|aug...,NaN,RGD:1603606,UniProtKB:D3DVK2|UniProtKB:C9JRR0|UniProtKB:B8...,SO:0001217,protein_coding_gene,Enables neuropeptide hormone activity. Involve...,NaN,Enables neuropeptide hormone activity. Involve...,GRCh38,2,106063241,106078155,+

In [6]:
orth = await ann.get_orthologs(["TP53", "BRCA1", "EGFR", "RPA1", "CELSR3", "NOTAGENE"], taxon="human", limit=2)
orth["Gene2SpeciesTaxonCommonName"] = orth["Gene2SpeciesTaxonID"].map(taxon_mapper(TaxonField.COMMON_NAME))
orth

,query,match_kind,Gene2ID,Gene2Symbol,Gene2SpeciesTaxonID,Gene2SpeciesTaxonCommonName
0,TP53,OFFICIAL_SYMBOL,Xenbase:XB-GENE-6252168,tp53.L,NCBITaxon:8355,african clawed frog
1,TP53,OFFICIAL_SYMBOL,Xenbase:XB-GENE-484286,tp53,NCBITaxon:8364,western clawed frog
2,TP53,OFFICIAL_SYMBOL,FB:FBgn0039044,p53,NCBITaxon:7227,fly
3,TP53,OFFICIAL_SYMBOL,MGI:98834,Trp53,NCBITaxon:10090,mouse
4,TP53,OFFICIAL_SYMBOL,ZFIN:ZDB-GENE-990415-270,tp53,NCBITaxon:7955,zebrafish
5,TP53,OFFICIAL_SYMBOL,Xenbase:XB-GENE-17346471,tp53.S,NCBITaxon:8355,african clawed frog
6,TP53,OFFICIAL_SYMBOL,RGD:3889,Tp53,NCBITaxon:10116,rat
7,TP53,SYNONYM,MGI:1351320,Trp53bp1,NCBITaxon:10090,mouse
8,TP53,SYNONYM,Xenbase:XB-GENE-17336999,tp53bp1.L,NCBITaxon:8355,african clawed frog
9,TP53,SYNONYM,Xenbase:XB-GENE-1010618,tp53bp1.S,NCBITaxon:8355,african clawed frog
10,TP53,SYNONYM,SGD:S000002625,RAD9,NCBITaxon:559292,yeast
11,TP53,SYNONYM,RGD:1308039,Tp53bp1,NCBITaxon:10116,rat
12,TP53,SYNONYM,Xenbase:XB-GENE-1010615,tp53bp1,NCBITaxon:8364,western clawed frog
13,TP53,SYNONYM,ZFIN:ZDB-GENE-030131-3695,tp53bp1,NCBITaxon:7955,zebrafish
14,TP53,SYNONYM,WB:WBGene00002027,hsr-9,NCBITaxon:6239,worm
15,BRCA1,OFFICIAL_SYMBOL,RGD:2218,Brca1,NCBITaxon:10116,rat
16,BRCA1,OFFICIAL_SYMBOL,Xenbase:XB-GENE-6254021,brca1.L,NCBITaxon:8355,african clawed frog
17,BRCA1,OFFICIAL_SYMBOL,WB:WBGene00000264,brc-1,NCBITaxon:6239,worm
18,BRCA1,OFFICIAL_SYMBOL,MGI:104537,Brca1,NCBITaxon:10090,mouse
19,BRCA1,OFFICIAL_SYMBOL,Xenbase:XB-GENE-490624,brca1,NCBITaxon:8364,western clawed frog
20,EGFR,OFFICIAL_SYMBOL,WB:WBGene00002299,let-23,NCBITaxon:6239,worm
21,EGFR,OFFICIAL_SYMBOL,RGD:2543,Egfr,NCBITaxon:10116,rat
22,EGFR,OFFICIAL_SYMBOL,Xenbase:XB-GENE-6067152,egfr,NCBITaxon:8364,western clawed frog
23,EGFR,OFFICIAL_SYMBOL,Xenbase:XB-GENE-17334442,egfr.S,NCBITaxon:8355,african clawed frog
24,EGFR,OFFICIAL_SYMBOL,Xenbase:XB-GENE-6067157,egfr.L,NCBITaxon:8355,african clawed frog
25,EGFR,OFFICIAL_SYMBOL,FB:FBgn0003731,Egfr,NCBITaxon:7227,fly
26,EGFR,OFFICIAL_SYMBOL,MGI:95294,Egfr,NCBITaxon:10090,mouse
27,EGFR,OFFICIAL_SYMBOL,ZFIN:ZDB-GENE-030918-1,egfra,NCBITaxon:7955,zebrafish
28,EGFR,OFFICIAL_SYMBOL,ZFIN:ZDB-GENE-100308-1,egfrb,NCBITaxon:7955,zebrafish
29,RPA1,OFFICIAL_SYMBOL,WB:WBGene00017546,rpa-1,NCBITaxon:6239,worm
30,RPA1,OFFICIAL_SYMBOL,MGI:1915525,Rpa1,NCBITaxon:10090,mouse
31,RPA1,OFFICIAL_SYMBOL,Xenbase:XB-GENE-945055,rpa1.L,NCBITaxon:8355,african clawed frog
32,RPA1,OFFICIAL_SYMBOL,FB:FBgn0010173,RPA1,NCBITaxon:7227,fly
33,RPA1,OFFICIAL_SYMBOL,Xenbase:XB-GENE-945047,rpa1,NCBITaxon:8364,western clawed frog
34,RPA1,OFFICIAL_SYMBOL,SGD:S000000065,RFA1,NCBITaxon:559292,yeast
35,RPA1,OFFICIAL_SYMBOL,Xenbase:XB-GENE-17344439,rpa1.S,NCBITaxon:8355,african clawed frog
36,RPA1,OFFICIAL_SYMBOL,ZFIN:ZDB-GENE-030912-3,rpa1,NCBITaxon:7955,zebrafish
37,RPA1,OFFICIAL_SYMBOL,WB:WBGene00019859,R03H10.7,NCBITaxon:6239,worm
38,RPA1,OFFICIAL_SYMBOL,RGD:1307376,Rpa1,NCBITaxon:10116,rat
39,RPA1,SYNONYM,ZFIN:ZDB-GENE-030131-5286,polr1a,NCBITaxon:7955,zebrafish
40,RPA1,SYNONYM,MGI:1096397,Polr1a,NCBITaxon:10090,mouse
41,RPA1,SYNONYM,FB:FBgn0019938,Polr1A,NCBITaxon:7227,fly
42,RPA1,SYNONYM,RGD:620824,Polr1a,NCBITaxon:10116,rat
43,RPA1,SYNONYM,Xenbase:XB-GENE-1005160,polr1a,NCBITaxon:8364,western clawed frog
44,RPA1,SYNONYM,Xenbase:XB-GENE-1005163,polr1a.L,NCBITaxon:8355,african clawed frog
45,RPA1,SYNONYM,SGD:S000005868,RPA190,NCBITaxon:559292,yeast
46,RPA1,SYNONYM,WB:WBGene00012999,rpoa-1,NCBITaxon:6239,worm
47,CELSR3,OFFICIAL_SYMBOL,Xenbase:XB-GENE-852799,celsr3,NCBITaxon:8364,western clawed frog
48,CELSR3,OFFICIAL_SYMBOL,Xenbase:XB-GENE-17342205,celsr3.L,NCBITaxon:8355,african clawed frog
49,CELSR3,OFFICIAL_SYMBOL,WB:WBGene00001475,fmi-1,NCBITaxon:6239,worm
50,CELSR3,OFFICIAL_SYMBOL,RGD:621787,Celsr3,NCBITaxon:10116,rat
51,CELSR3,OFFICIAL_SYMBOL,Xenbase:XB-GENE-17342206,celsr3.S,NCBITaxon:8355,african clawed frog
52,CELSR3,OFFICIAL_SYMBOL,FB:FBgn0024836,stan,NCBITaxon:7227,fly
53,CELSR3,OFFICIAL_SYMBOL,ZFIN:ZDB-GENE-070122-3,celsr3,NCBITaxon:7955,zebrafish
54,CELSR3,OFFICIAL_SYMBOL,MGI:1858236,Celsr3,NCBITaxon:10090,mouse
55,NOTAGENE,None,NaN,NaN,NaN,NaN

In [7]:
# Filter-then-requery: pull the mouse orthologs back out as a fresh gene list.
mouse_ids = orth.loc[orth.Gene2SpeciesTaxonCommonName == "mouse", "Gene2ID"].dropna().unique().tolist()
mouse_ids

['MGI:98834',
 'MGI:1351320',
 'MGI:104537',
 'MGI:95294',
 'MGI:1915525',
 'MGI:1096397',
 'MGI:1858236']

In [8]:
# Per-gene API path (phenotypes have no bulk TSV): paginated + cached under cache/api/phenotypes/.
pheno = await ann.annotate(mouse_ids, AGRDataset.PHENOTYPES, taxon="mouse")
pheno

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,...,GeneMODDescription,Assembly,Chromosome,StartPosition,EndPosition,Strand,gene_id,phenotypeStatement,references,has.phenotypes
0,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,MGI:98834,abnormal abdominal lymph node morphology,PMID:24013501,True
1,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,MGI:98834,abnormal apoptosis,PMID:14702042,True
2,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,MGI:98834,abnormal atrioventricular cushion morphology,PMID:25119037,True
3,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,MGI:98834,abnormal cardiac outflow tract development,PMID:25119037,True
4,MGI:98834,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:98834,Trp53,p53|p44,NaN,NaN,UniProtKB:A0A158SIS7|UniProtKB:A0A5Q0MU23|UniP...,...,Mutations in this locus affect cell-cycle regu...,GRCm39,11,69471174,69482699,+,MGI:98834,abnormal cardiovascular system physiology,PMID:17334357,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,MGI:1858236,impaired coordination,PMID:15778712,True
687,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,MGI:1858236,impaired neuronal migration,PMID:19332558,True
688,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,MGI:1858236,meteorism,PMID:15778712,True
689,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,MGI:1858236,"neonatal lethality, complete penetrance",PMID:19332558|PMID:15778712,True
690,MGI:1858236,PRIMARY_ID,NCBITaxon:10090,Mus musculus,MGI:1858236,Celsr3,flamingo|Fmi1|Adgrc3|mKIAA0812,NaN,NaN,UniProtKB:A0A076N9U7|UniProtKB:A0A0A6YW76|UniP...,...,Mice homozygous for a null allele exhibit neon...,GRCm39,9,108703244,108730168,+,MGI:1858236,respiratory failure,PMID:15778712,True

In [11]:
#brainspan_path = "/nfs/xing_lab/lab02/Data_Raw/Xiaolong/HumanCommon/Expression/BrainSpan/20190508BrainSpanGeneExpression.csv"
sfari_path = "/lab01/Projects/Lionel_Projects/biodatabases/SFARI/SFARI-Gene_genes_08-19-2024release_10-06-2024export.csv"
cao_ndd_path = "/lab01/Projects/Lionel_Projects/biodatabases/Cao_NDD_Candidate_Genes.tsv"

#brainspan_df = pd.read_csv(brainspan_path, sep="\t", comment="#")
sfari_df = pd.read_csv(sfari_path, sep=",", comment="#")
cao_ndd_df = pd.read_csv(cao_ndd_path, sep="\t", comment="#")

# Prepend ENSEMBL prefix to BrainSpan gene IDs to match the format in the gene index, enabling cross-referencing during ingestion.
#brainspan_df = brainspan_df.copy()
#brainspan_df['ensembl_gene_id_full'] = brainspan_df['ensembl_gene_id'].map(lambda x: f"ENSEMBL:{x}")

#brainspan_res, brainspan_unmapped = await ann.ingest_annotation(brainspan_df, "brainspan", gene_id_column=["geneSymbol", "ensembl_gene_id_full"], taxon="human", override=False, case_insensitive=True)
sfari_res, sfari_unmapped = await ann.ingest_annotation(sfari_df, "sfari", gene_id_column="gene-symbol", taxon="human", override=False, case_insensitive=True)
cao_ndd_res, cao_ndd_unmapped = await ann.ingest_annotation(cao_ndd_df, "cao_ndd", gene_id_column="hgnc_id", taxon="human", override=False, case_insensitive=True)

# print("BrainSpan Ingestion Result:", brainspan_res)
# print("SFARI Ingestion Result:", sfari_res)
# print("Cao NDD Ingestion Result:", cao_ndd_res)

In [ ]:
alleles = await ann.annotate(["TP53", "BRCA1", "EGFR", "ANK3"], taxon="human")
display(alleles)

,query,match_kind,Taxon,SpeciesName,GeneId,GeneSymbol,GeneSynonyms,GeneSystematicName,GeneSecondaryIds,GeneCrossReferences,...,sfari.gene-symbol,sfari.gene-name,sfari.ensembl-id,sfari.chromosome,sfari.genetic-category,sfari.gene-score,sfari.syndromic,sfari.eagle,sfari.number-of-reports,has.sfari
0,TP53,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:11998,TP53,LFS1|TRP53|FLJ92943|P53|phosphoprotein p53|cel...,NaN,RGD:70502,RGD:70502|ENSEMBL:ENSG00000141510|NCBI_Gene:71...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,BRCA1,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:1100,BRCA1,BROVCA1|IRIS|PSCP|BRCAI|BRCC1|RNF53|breast can...,NaN,RGD:69132,RGD:69132|ENSEMBL:ENSG00000012048|NCBI_Gene:67...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,EGFR,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:3236,EGFR,ERBB|HER1|mENA|ERBB1|PIG61|receptor tyrosine-p...,NaN,RGD:69152,RGD:69152|ENSEMBL:ENSG00000146648|NCBI_Gene:19...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,ANK3,OFFICIAL_SYMBOL,NCBITaxon:9606,Homo sapiens,HGNC:494,ANK3,FLJ45464|ANKYRIN-G|ankyrin-3|ANK-3|ankyrin G11...,NaN,RGD:1318779,RGD:1318779|ENSEMBL:ENSG00000151150|NCBI_Gene:...,...,ANK3,ankyrin 3,ENSG00000151150,10,"Rare Single Gene Mutation, Genetic Association...",1.0,0.0,7.3,34.0,True

In [13]:
test = await ann.annotate(["TP53", "BRCA1", "EGFR"], AGRDataset.ALLELES, "sfari", "cao_ndd", taxon="human")
# display(test)
display(test.loc[:, test.columns.str.startswith("has.") | test.columns.str.startswith("GeneId")])

           GeneId  has.alleles has.sfari has.cao_ndd
0      HGNC:11998         True     False       False
1      HGNC:11998         True     False       False
2      HGNC:11998         True     False       False
3      HGNC:11998         True     False       False
4      HGNC:11998         True     False       False
...           ...          ...       ...         ...
18834   HGNC:3236         True     False        True
18835   HGNC:3236         True     False        True
18836   HGNC:3236         True     False        True
18837   HGNC:3236         True     False        True
18838   HGNC:3236         True     False        True

[18839 rows x 4 columns]

In [ ]:
# from preprocess import resolve_cache_dir, _load_gene_records
# from annotator import Annotator

# from pathlib import Path
# import pandas as pd

# cache_dir = Path("/lab01/Projects/Lionel_Projects/alliance_wrapper/cache")
# ann = Annotator(cache_dir)
# records = await _load_gene_records(
#     cache_dir, refresh=False, client=ann._client, downloader=ann._downloader
# )
# display(records)

In [ ]:
# id_columns = {
#     "GeneId":              "PRIMARY_ID",
#     "GeneSecondaryIds":    "SECONDARY_ID",
#     "GeneSymbol":          "OFFICIAL_SYMBOL",
#     "GeneSynonyms":        "SYNONYM",
#     "GeneCrossReferences": "CROSS_REFERENCE",
# }

In [ ]:
# lookup = (
#     records[list(id_columns.keys())]
#     .rename_axis("row")
#     .reset_index() # reset index to have a column for row numbers
#     .melt(id_vars="row", var_name="kind", value_name="key")
#     .dropna(subset=["key"]) # drop rows where key is NaN
#     .assign(key=lambda df: df["key"].str.split("|")) # split the key column by "|"
#     .explode("key", ignore_index=True) # explode the list of keys into separate rows
# )
# lookup["kind"] = lookup["kind"].map(id_columns) # map the kind to the new column names
# display(lookup)