In [ ]:
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())  # load .env from repo root

from client import AsyncAGRClient
from cache import CacheManager

from endpoints import get_orthologs, get_phenotypes, get_phenotypes_download, get_alleles

from utils import query_gene_ids, normalize_symbols, ingest_annotation, query_annotations, annotate

In [2]:
gene_symbols = ["BRCA1", "TP53", "EGFR", "CELSR3", "RPA1", "dummy", "DUMMY", " ", "brca1", "rpa1"]
gene_ids = normalize_symbols(gene_symbols)
print(gene_ids)

['HGNC:1100', 'HGNC:11998', 'HGNC:3236', 'HGNC:3230', 'FB:FBgn0010173', 'HGNC:10289', 'Xenbase:XB-GENE-490624', 'ZFIN:ZDB-GENE-030912-3', 'Xenbase:XB-GENE-945047']

In [3]:
cache = CacheManager()
client = AsyncAGRClient()

In [4]:
orthologs_df, _ = await query_gene_ids(get_orthologs, cache, gene_ids, client)
display(orthologs_df)
print(orthologs_df.shape)

                subject_id                object_id confidence
0                HGNC:1100                 RGD:2218       high
1                HGNC:1100   Xenbase:XB-GENE-490624       high
2                HGNC:1100               MGI:104537       high
3                HGNC:1100        WB:WBGene00000264       high
4                HGNC:1100  Xenbase:XB-GENE-6254021       high
..                     ...                      ...        ...
63  Xenbase:XB-GENE-945047              MGI:1915525       high
64  Xenbase:XB-GENE-945047   Xenbase:XB-GENE-945055       high
65  Xenbase:XB-GENE-945047           SGD:S000000065       high
66  Xenbase:XB-GENE-945047              RGD:1307376       high
67  Xenbase:XB-GENE-945047        WB:WBGene00017546       high

[68 rows x 3 columns]

(68, 3)

In [5]:
phenotypes_download_df, _ = await query_gene_ids(get_phenotypes, cache, gene_ids, client)
display(phenotypes_download_df)
print(phenotypes_download_df.shape)

                subject_id                                 phenotypeStatement
0                HGNC:1100                               Abdominal distention
1                HGNC:1100                                     Abdominal pain
2                HGNC:1100                         Abnormal aortic morphology
3                HGNC:1100                   Abnormal aortic valve morphology
4                HGNC:1100                 Abnormal cardiac septum morphology
..                     ...                                                ...
81  ZFIN:ZDB-GENE-030912-3                                head flat, abnormal
82  ZFIN:ZDB-GENE-030912-3                           heart necrotic, abnormal
83  ZFIN:ZDB-GENE-030912-3          neuromast development disrupted, abnormal
84  ZFIN:ZDB-GENE-030912-3  posterior lateral line neuromast has fewer par...
85  ZFIN:ZDB-GENE-030912-3                 whole organism viability, abnormal

[86 rows x 2 columns]

(86, 2)

In [6]:
phenotypes_download_df, _ = await query_gene_ids(get_phenotypes_download, cache, gene_ids, client)
display(phenotypes_download_df)
print(phenotypes_download_df.shape)

,Phenotype,Genetic Entity ID,Genetic Entity Name,Genetic Entity Type
0,Abdominal distention,HGNC:1100,BRCA1,gene
1,Abdominal pain,HGNC:1100,BRCA1,gene
2,Abnormal aortic morphology,HGNC:1100,BRCA1,gene
3,Abnormal aortic valve morphology,HGNC:1100,BRCA1,gene
4,Abnormal cardiac septum morphology,HGNC:1100,BRCA1,gene
...,...,...,...,...
437,"heart necrotic, abnormal",ZFIN:ZDB-FISH-150901-24729,rpa1<sup>hi2618Tg</sup>,fish
438,"neuromast development disrupted, abnormal",ZFIN:ZDB-FISH-190822-3,rpa1<sup>la010246Tg/la010246Tg</sup>,fish
439,posterior lateral line neuromast has fewer par...,ZFIN:ZDB-FISH-190822-3,rpa1<sup>la010246Tg/la010246Tg</sup>,fish
440,"whole organism viability, abnormal",ZFIN:ZDB-FISH-150901-10375,rpa1<sup>hi2877bTg/hi2877bTg</sup>,fish
441,"whole organism viability, abnormal",ZFIN:ZDB-FISH-150901-7654,rpa1<sup>hi2618Tg/hi2618Tg</sup>,fish

(442, 4)

In [7]:
alleles_df, _ = await query_gene_ids(get_alleles, cache, gene_ids, client)
display(alleles_df)
print(alleles_df.shape)

,allele_id,symbol,alteration_type,has_phenotype,has_disease,variant_type,chromosome,assembly,start,end,ref,alt,hgvs_g,hgvs_c,most_severe_consequence,rs_id
0,rs273897661,NC_000017.11:g.43124110A>C,variant,False,False,SNP,17,GRCh38,43124110.0,43124110.0,A,C,NC_000017.11:g.43124110A>C,ENSEMBL:ENST00000352993.7:c.-14T>G,LOW,rs273897661
1,rs273897661,NC_000017.11:g.43124110A>G,variant,False,False,SNP,17,GRCh38,43124110.0,43124110.0,A,G,NC_000017.11:g.43124110A>G,ENSEMBL:ENST00000352993.7:c.-14T>C,LOW,rs273897661
2,rs2552254599,NC_000017.11:g.43104909dup,variant,False,False,insertion,17,GRCh38,43104909.0,43104909.0,NaN,A,NC_000017.11:g.43104909dup,ENSEMBL:ENST00000352993.7:c.260dup,HIGH,rs2552254599
3,rs2054767462,NC_000017.11:g.43106451T>C,variant,False,False,SNP,17,GRCh38,43106451.0,43106451.0,T,C,NC_000017.11:g.43106451T>C,ENSEMBL:ENST00000352993.7:c.212+5A>G,LOW,rs2054767462
4,rs80357591,NC_000017.11:g.43106491del,variant,False,False,deletion,17,GRCh38,43106490.0,43106491.0,T,NaN,NC_000017.11:g.43106491del,ENSEMBL:ENST00000352993.7:c.177del,HIGH,rs80357591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19320,,sa2803,allele with one variant,False,False,point_mutation,15,GRCz11,26508544.0,26508544.0,A,G,NC_007126.7:g.26508544A>G,ENSEMBL:ENSDART00000032880.1:c.1506+2T>C,HIGH,None
19321,,la019268Tg,allele,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
19322,,hi2618Tg,allele,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
19323,,la010246Tg,allele,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
19324,,hi2877bTg,allele,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

(19325, 16)

In [8]:
await client.close()