In [1]:
from client import AsyncAGRClient
from cache import CacheManager

from endpoints.orthologs import get_orthologs
from endpoints.phenotypes import get_phenotypes
from endpoints.phenotypes_download import get_phenotypes_download
from endpoints.alleles import get_alleles

from utils import query_gene_ids

In [2]:
gene_ids = ["RGD:1307376", "HGNC:1100"]
cache = CacheManager()
client = AsyncAGRClient()

In [3]:
orthologs_df, raw_df = await query_gene_ids(get_orthologs, cache, gene_ids, client)
display(orthologs_df)
display(raw_df)

     subject_id                object_id confidence
0   RGD:1307376        WB:WBGene00019859   moderate
1   RGD:1307376              MGI:1915525       high
2   RGD:1307376        WB:WBGene00019858   moderate
3   RGD:1307376   Xenbase:XB-GENE-945047       high
4   RGD:1307376   ZFIN:ZDB-GENE-030912-3       high
5   RGD:1307376           FB:FBgn0010173       high
6   RGD:1307376        WB:WBGene00017546       high
7   RGD:1307376           SGD:S000000065       high
8   RGD:1307376               HGNC:10289       high
9     HGNC:1100                 RGD:2218       high
10    HGNC:1100   Xenbase:XB-GENE-490624       high
11    HGNC:1100               MGI:104537       high
12    HGNC:1100        WB:WBGene00000264       high
13    HGNC:1100  Xenbase:XB-GENE-6254021       high

Empty DataFrame
Columns: []
Index: []

In [4]:
phenotypes_df, raw_df = await query_gene_ids(get_phenotypes, cache, gene_ids, client)
display(phenotypes_df)

   subject_id                              phenotypeStatement
0   HGNC:1100                            Abdominal distention
1   HGNC:1100                                  Abdominal pain
2   HGNC:1100                      Abnormal aortic morphology
3   HGNC:1100                Abnormal aortic valve morphology
4   HGNC:1100              Abnormal cardiac septum morphology
5   HGNC:1100              Abnormal carotid artery morphology
6   HGNC:1100                      Abnormal eyelid morphology
7   HGNC:1100              Abnormal fallopian tube morphology
8   HGNC:1100                       Abnormal femur morphology
9   HGNC:1100                        Abnormal foot morphology
10  HGNC:1100                 Abnormal localization of kidney
11  HGNC:1100                     Abnormal morphology of ulna
12  HGNC:1100              Abnormal nervous system morphology
13  HGNC:1100                       Abnormal pinna morphology
14  HGNC:1100                   Abnormal preputium morphology
15  HGNC:1100                       Abnormal renal morphology
16  HGNC:1100                      Abnormal testis morphology
17  HGNC:1100                       Abnormal thumb morphology
18  HGNC:1100  Abnormality of blood and blood-forming tissues
19  HGNC:1100             Abnormality of chromosome stability

In [5]:
phenotypes_df, raw_df = await query_gene_ids(get_phenotypes_download, cache, gene_ids, client)
display(phenotypes_df)

,Phenotype,Genetic Entity ID,Genetic Entity Name,Genetic Entity Type
0,Abdominal distention,HGNC:1100,BRCA1,gene
1,Abdominal pain,HGNC:1100,BRCA1,gene
2,Abnormal aortic morphology,HGNC:1100,BRCA1,gene
3,Abnormal aortic valve morphology,HGNC:1100,BRCA1,gene
4,Abnormal cardiac septum morphology,HGNC:1100,BRCA1,gene
...,...,...,...,...
161,Underdeveloped nasal alae,HGNC:1100,BRCA1,gene
162,Upslanted palpebral fissure,HGNC:1100,BRCA1,gene
163,Ventriculomegaly,HGNC:1100,BRCA1,gene
164,Visual impairment,HGNC:1100,BRCA1,gene
165,Weight loss,HGNC:1100,BRCA1,gene

In [6]:
alleles_df, raw_df = await query_gene_ids(get_alleles, cache, gene_ids, client)
display(alleles_df)

,allele_id,symbol,alteration_type,has_phenotype,has_disease,variant_type,chromosome,assembly,start,end,ref,alt,hgvs_g,hgvs_c,most_severe_consequence,rs_id
0,rs3321772432,NC_051345.1:g.60170827G>A,variant,False,False,SNP,10,mRatBN7.2,60170827,60170827,G,A,NC_051345.1:g.60170827G>A,ENSEMBL:ENSRNOT00000004229.5:c.88+1181C>T,MODIFIER,rs3321772432
1,ENSEMBL:ENSRNOT00000004229.5:c.88+771_88+791del,NC_051345.1:g.60171217_60171237del,variant,False,False,deletion,10,mRatBN7.2,60171216,60171237,ACACACCCACCCACCCACCAC,NaN,NC_051345.1:g.60171217_60171237del,ENSEMBL:ENSRNOT00000004229.5:c.88+771_88+791del,MODIFIER,NaN
2,rs107135259,NC_051345.1:g.60188566T>C,variant,False,False,SNP,10,mRatBN7.2,60188566,60188566,T,C,NC_051345.1:g.60188566T>C,ENSEMBL:ENSRNOT00000090262.3:c.239+2868A>G,MODIFIER,rs107135259
3,rs3321722558,NC_051345.1:g.60188596T>C,variant,False,False,SNP,10,mRatBN7.2,60188596,60188596,T,C,NC_051345.1:g.60188596T>C,ENSEMBL:ENSRNOT00000090262.3:c.239+2838A>G,MODIFIER,rs3321722558
4,rs3321772553,NC_051345.1:g.60161972T>A,variant,False,False,SNP,10,mRatBN7.2,60161972,60161972,T,A,NC_051345.1:g.60161972T>A,ENSEMBL:ENSRNOT00000004229.5:c.486+15A>T,MODIFIER,rs3321772553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12778,rs1555590709,NC_000017.11:g.43093535G>C,variant,False,False,SNP,17,GRCh38,43093535,43093535,G,C,NC_000017.11:g.43093535G>C,ENSEMBL:ENST00000352993.7:c.670+2311C>G,MODERATE,rs1555590709
12779,rs1555590709,NC_000017.11:g.43093535G>T,variant,False,False,SNP,17,GRCh38,43093535,43093535,G,T,NC_000017.11:g.43093535G>T,ENSEMBL:ENST00000352993.7:c.670+2311C>A,MODERATE,rs1555590709
12780,rs80357129,NC_000017.11:g.43093597G>C,variant,False,False,SNP,17,GRCh38,43093597,43093597,G,C,NC_000017.11:g.43093597G>C,ENSEMBL:ENST00000352993.7:c.670+2249C>G,MODERATE,rs80357129
12781,rs62625305,NC_000017.11:g.43093620A>G,variant,False,False,SNP,17,GRCh38,43093620,43093620,A,G,NC_000017.11:g.43093620A>G,ENSEMBL:ENST00000352993.7:c.670+2226T>C,MODERATE,rs62625305
12782,rs80356834,NC_000017.11:g.43093638T>G,variant,False,False,SNP,17,GRCh38,43093638,43093638,T,G,NC_000017.11:g.43093638T>G,ENSEMBL:ENST00000352993.7:c.670+2208A>C,HIGH,rs80356834

In [7]:
alleles_df, raw_df = await query_gene_ids(get_alleles, cache, ["RGD:1307376"], client)
display(alleles_df)

,allele_id,symbol,alteration_type,has_phenotype,has_disease,variant_type,chromosome,assembly,start,end,ref,alt,hgvs_g,hgvs_c,most_severe_consequence,rs_id
0,rs3321772432,NC_051345.1:g.60170827G>A,variant,False,False,SNP,10,mRatBN7.2,60170827,60170827,G,A,NC_051345.1:g.60170827G>A,ENSEMBL:ENSRNOT00000004229.5:c.88+1181C>T,MODIFIER,rs3321772432
1,ENSEMBL:ENSRNOT00000004229.5:c.88+771_88+791del,NC_051345.1:g.60171217_60171237del,variant,False,False,deletion,10,mRatBN7.2,60171216,60171237,ACACACCCACCCACCCACCAC,NaN,NC_051345.1:g.60171217_60171237del,ENSEMBL:ENSRNOT00000004229.5:c.88+771_88+791del,MODIFIER,NaN
2,rs107135259,NC_051345.1:g.60188566T>C,variant,False,False,SNP,10,mRatBN7.2,60188566,60188566,T,C,NC_051345.1:g.60188566T>C,ENSEMBL:ENSRNOT00000090262.3:c.239+2868A>G,MODIFIER,rs107135259
3,rs3321722558,NC_051345.1:g.60188596T>C,variant,False,False,SNP,10,mRatBN7.2,60188596,60188596,T,C,NC_051345.1:g.60188596T>C,ENSEMBL:ENSRNOT00000090262.3:c.239+2838A>G,MODIFIER,rs3321722558
4,rs3321772553,NC_051345.1:g.60161972T>A,variant,False,False,SNP,10,mRatBN7.2,60161972,60161972,T,A,NC_051345.1:g.60161972T>A,ENSEMBL:ENSRNOT00000004229.5:c.486+15A>T,MODIFIER,rs3321772553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,rs3321847437,NC_051345.1:g.60191928C>T,variant,False,False,SNP,10,mRatBN7.2,60191928,60191928,C,T,NC_051345.1:g.60191928C>T,ENSEMBL:ENSRNOT00000090262.3:c.130+240G>A,MODIFIER,rs3321847437
183,rs3321582856,NC_051345.1:g.60192016C>T,variant,False,False,SNP,10,mRatBN7.2,60192016,60192016,C,T,NC_051345.1:g.60192016C>T,ENSEMBL:ENSRNOT00000090262.3:c.130+152G>A,MODIFIER,rs3321582856
184,rs3321582777,NC_051345.1:g.60192211C>T,variant,False,False,SNP,10,mRatBN7.2,60192211,60192211,C,T,NC_051345.1:g.60192211C>T,ENSEMBL:ENSRNOT00000090262.3:c.87G>A,LOW,rs3321582777
185,rs3321929330,NC_051345.1:g.60192612G>A,variant,False,False,SNP,10,mRatBN7.2,60192612,60192612,G,A,NC_051345.1:g.60192612G>A,ENSEMBL:ENSRNOT00000090262.3:c.52-366C>T,MODIFIER,rs3321929330
186,ENSEMBL:ENSRNOT00000090262.3:c.52-700del,NC_051345.1:g.60192946del,variant,False,False,deletion,10,mRatBN7.2,60192945,60192946,T,NaN,NC_051345.1:g.60192946del,ENSEMBL:ENSRNOT00000090262.3:c.52-700del,MODIFIER,NaN

In [8]:
await client.close()